version: "3"
services:
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:lts
        ports:
            - "8080:8080"
        volumes:
            - $PWD/jenkins_home:/var/jenkins_home
        networks:
            - net
        dns:
            - 8.8.8.8
    remote_host:
        container_name: remote-host
        image: remote-host
        build:
            context: centos
        networks:
            - net
    db_host:
        container_name: db
        image: mysql:5.7
        volumes:
            - $PWD/db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
        networks:
            - net
networks:
    net:
