version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672         # MQ listens here 
            - 15672:15672       # For management console
