[package]
name = "combpq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "31.0.0"
futures = "0.3.28"
object_store = "0.7.1"
tar = "0.4.40"
tokio = "1.33.0"
