
up:
	docker-compose up -d

down:
	docker-compose down

mongo:
	docker exec -it mongo_db mongo -u root -p 1234

mongo-admin:
	docker exec -it mongo_db mongo admin -u root -p 1234

run-app-local:
	python api/run_hack_api.py
