version: '3'
services:
    stf_db:
        container_name: stf_db
        hostname: stf_db
        image: timescale/timescaledb-postgis:latest-pg12
        volumes:
            - ./stf_db/stf_db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - ./stf_db/.env
        networks:
            - stf_net
    grafana:
        container_name: grafana
        hostname: grafana
        image: grafana/grafana
        ports:
            - "3000:3000"
        networks:
            - stf_net
        volumes:
            - grafana_data:/var/lib/grafana
        env_file:
            - ./grafana/.env
    # TODO:
    # stf_geoserver:
networks:
    stf_net:
volumes:
    grafana_data:
